Created support template under docs folder
ansible-collections/dellemc.enterprise_sonic pull request #143
Opened 2022-11-28 10:02 UTC by kannankvs

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-01-04 04:15 UTC, kannankvs commented
Was closed by mistake. Re opening it again

2023-02-15 08:28 UTC, kannankvs commented
@mingjunzhang2019  Can you please review as early as possible ?

2023-02-15 20:42 UTC, jeff-yin commented
Mingjun is on PTO -- @stalabi1 and/or @kerry-meyer  will need to review.

2023-02-15 20:45 UTC, jeff-yin commented on docs/SUPPORT.md
> +  * To provide feedback to the development team, send an email to **<email_id>**.
I don't think we should use e-mail to provide/receive feedback. If folks have feedback they should just open an issue. The development team is subscribed to the repositories so we will get notified via e-mail anyway.

2023-02-15 21:59 UTC, jeff-yin requested changes

2023-02-15 21:59 UTC, jeff-yin commented on docs/SUPPORT.md
> +  * If any requirements have not been addressed, then create an issue [here](https://github.com/dell/<repo name>/issues).
Why don't we link this repo directly? i.e., `https://github.com/ansible-collections/dellemc.enterprise_sonic/issues`

2023-02-15 21:59 UTC, jeff-yin commented on docs/SUPPORT.md
> +  * To report any issue, create an issue [here](https://github.com/dell/<repo name>/issues).
Why don't we link to this repo directly? i.e., `https://github.com/ansible-collections/dellemc.enterprise_sonic/issues`

2023-02-28 07:10 UTC, kannankvs commented
We are unable to commit in this PR due to "head repository deletion" issue. Hence we raised a new [PR#162](https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/162) and copied all the comments from this PR to the new PR. This PR is no more valid and hence we are closing it.

2023-02-28 07:10 UTC, closed without merging