LLDP Global module
ansible-collections/dellemc.enterprise_sonic pull request #171
Opened 2023-02-28 09:17 UTC by divya-balasubramania

##### SUMMARY
LLDP_GLOBAL Module implementation

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
sonic_lldp_global

##### ADDITIONAL INFORMATION

1. Regression test HTML report:  

2. Regression test detailed log:

3. Show running-config and respective facts gathered:

2023-03-07 08:30 UTC, ArunSaravananBalachandran requested changes

2023-03-07 08:30 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_lldp_global.py
> +          system_capabilities: True
Please change the value to `true`

2023-03-07 08:30 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_lldp_global.py
> +                  management_address: True
Please change the value to `true`

2023-03-07 08:30 UTC, ArunSaravananBalachandran commented on tests/regression/roles/sonic_lldp_global/defaults/main.yml
> +           system_capabilities: true
Please update the indentation to be uniform across blocks for all test cases.

2023-03-07 08:30 UTC, ArunSaravananBalachandran commented on tests/regression/roles/sonic_lldp_global/defaults/main.yml
> +
Please remove trailing whitespaces in this file, cleanup_tests.yaml, preparation_tests.yaml and tasks_template_del.yaml

2023-03-07 08:30 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/lldp_global/lldp_global.py
> +            payload = {'openconfig-lldp:enabled': command['enable']}
Replace double quotes with single quote for keys in config and facts.

2023-03-13 10:24 UTC, divya-balasubramania commented
Addressed review comments and re-executed the test cases.

Regression test HTML report:

[lldp_global_regression_results.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10956240/regression-2023-03-13-15-19-50.pdf)

Regression test detailed terminal log:

[lldp_global_detailed_log_latest.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/10956248/lldp_global_detailed_log_latest.txt)

2023-03-23 09:53 UTC, ArunSaravananBalachandran requested changes

2023-03-23 09:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/facts/lldp_global/lldp_global.py
> +        return lldp_global_data
Default settings of 'enabled' and 'tlv_select' options needs to be handled.

2023-03-23 09:53 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_lldp_global.py
> +    configuration applied on participating interfaces.
Please mention it as a list element to display it in a separate line.

2023-03-23 09:53 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_lldp_global.py
Please update the indentation to be uniform across blocks for all examples.

2023-03-23 09:53 UTC, ArunSaravananBalachandran commented on tests/regression/roles/sonic_lldp_global/defaults/main.yml
> +      system_name: CR1_sonic
Please include deletion of 'tlv_select' option as mentioned in the module example.

2023-03-23 09:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/lldp_global/lldp_global.py
> +                        want['tlv_select']['system_capabilities'] = False
As stated in the comment (https://github.com/ansible-network/resource_module_models/pull/196#discussion_r1101081735), the deletion needs to be carried out only for matching configurations. 

Usage of diff to get the matching configuration in other options will also work for tlv_select options.
Changing the option value will result in incorrect behaviour.

2023-03-23 09:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/lldp_global/lldp_global.py
> +        if 'system_description' in command:
Please include `None` value check.

2023-03-23 09:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/lldp_global/lldp_global.py
> +                    requests.append({'path': url, 'method': DELETE})
Both `True` and `False` values need to be handled.

2023-03-29 10:10 UTC, divya-balasubramania commented
Addressed review comments and re-executed the test cases.

Regression test HTML report:
[SONIC_LLDP_Global_Latest.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/11099391/SONIC_LLDP_Global_Latest.pdf)

2023-04-02 14:27 UTC, ArunSaravananBalachandran approved these changes

2023-04-26 05:25 UTC, merged