BGP Unit test code added
ansible-collections/dellemc.enterprise_sonic pull request #182
Opened 2023-03-13 11:02 UTC by kannankvs

##### SUMMARY
Adding unit tests code for BGP module

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
BGP Unit Test Module

2023-03-15 16:19 UTC, stalabi1 approved these changes

2023-03-17 23:59 UTC, kerry-meyer requested changes
There are a few additional test cases or test case attributes that would help to improve the UT coverage for this resource module. I have posted an inline comment and a "file" comment asking about the possibility of adding these:

  - additional "delete" attributes
  - testing of the "delete all" case.

2023-03-17 23:59 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_bgp.yaml
> +    config:
There are several attributes for which deletion is not being tested here. Is there a reason not to test deletion for these attributes?

- timers
- max_med
- bestpath/as_path/multipath_relax_as_set
- med/always_compare_med

2023-03-17 23:59 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_bgp.yaml
The "delete_all" case is currently not being tested in this file. If the "merged_01" case were duplicated/repeated as "merged_02", it could be followed by a "delete_all" test ("deleted_02"?) to test that code path.

2023-03-18 16:14 UTC, kannankvs commented
@kerry-meyer : The plan for UT is as follows. At first, we will write UT cases to meet 70% coverage. This is to put a TICK MARK against the OneAnsible requirement for UT. Later on, we need to plan to add more test cases to increase the coverage. Hence, I suggest to keep the above comments as FutureEnhancements and merge the PR with the currently available test cases.

2023-03-20 06:56 UTC, kerry-meyer commented
These first few UT PRs will be used by others as examples. It would be helpful if they at least did merge/delete for each defined attributed plus a "delete all" case. This should be the minimum requirement for each resource module. (I understand that each module may have some other special case branching that is beyond the scope of the initial UT implementation. But the items mentioned here seem like the basics, common to all resource modules.)

If there is a specific reason for this resource module's initial UT to omit the items mentioned in these comments for now, please explain the reason. (e.g. Why delete most of the attributes, but skip the ones mentioned above? If there are some special circumstances, we can consider deferring these items for now.)

2023-03-20 14:25 UTC, kannankvs commented
@kerry-meyer : Added the test cases that you mentioned.

2023-03-21 00:32 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_bgp.yaml
> +    config:
Thanks for adding these attributes to the test.

Resolved.

2023-03-21 00:35 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_bgp.yaml
Thanks for adding this test case.

Resolved.

2023-03-21 00:43 UTC, kerry-meyer approved these changes
Thank you for adding the additional requested test cases for this PR.

Note: The UT implementation in this resource module provides a good base example. For the remaining group of initial UT PRs, 70% coverage for the "target" resource module will be a sufficient UT criterion for approval and merging.

Approved.

2023-03-21 00:45 UTC, merged