BGP Neighbors module unit testing code added
ansible-collections/dellemc.enterprise_sonic pull request #187
Opened 2023-03-13 12:31 UTC by kannankvs

##### SUMMARY
BGP Neighbors module unit testing code added

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
BGP Neighbors Unit Testing

2023-03-29 23:49 UTC, kerry-meyer requested changes
I have posted a comment in the ".yaml" file: Please see if it is possible to increase the coverage above the current 59% level.

2023-03-29 23:49 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors.yaml
The UT coverage on the "config" file for this resource module is only 59%. My understanding is that this is below the target. If there are additional attributes that can be added to the test suite to increase the coverage, please add them. If there is a reason why the target can not be met at this time, please explain the considerations.

```
plugins/module_utils/network/sonic/config/bgp_neighbors/bgp_neighbors.py                  961    327    700    175   59%
```

2023-04-12 10:34 UTC, kannankvs commented on tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors.yaml
@kerry-meyer : UT coverage improvement is done. Kindly review.

2023-04-21 19:34 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_bgp_neighbors.yaml
Thanks for adding the additional coverage (and all of the other UT).

Approved.

2023-04-21 19:35 UTC, kerry-meyer approved these changes
Thanks for providing the UT for this module and making the additional changes to increase coverage.

Approved.

2023-04-21 19:35 UTC, merged