unit testing code for l2_interfaces module added
ansible-collections/dellemc.enterprise_sonic pull request #200
Opened 2023-03-31 12:13 UTC by kannankvs

##### SUMMARY
l2_interfaces module Unit Test Code Added

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
l2_interfaces module Unit Testing

2023-04-03 10:49 UTC, kannankvs commented
'replaced' and 'overridden' features are getting modified in l2_interfaces module by developers in parallel. This UT PR can be merged once if the PR for l2_interfaces module for 'replaced' and 'overridden' support is merged. If this UT requires rework after merging the l2_interfaces changes, it will be taken up after that gets merged.

2023-04-12 02:20 UTC, kerry-meyer requested changes
Please delete the argspec and module file from the change set. Let's wait until the real "replaced" and "overridden" support is added to do these changes. (This comment applies to any other UT modules where the module and argspec are being updated to add these states before the underlying code support has been provided.)

2023-04-12 02:20 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/argspec/l2_interfaces/l2_interfaces.py
Please delete this file from the change set. Let's wait until the real "replaced" and "overridden" support is added to do these changes. (This comment applies to any other UT modules where the module and argspec are being updated to add these states before the underlying code support has been provided.)

2023-04-12 02:20 UTC, kerry-meyer commented on plugins/modules/sonic_l2_interfaces.py
Please delete this file from the change set. Let's wait until the real "replaced" and "overridden" support is added to do these changes. (This comment applies to any other UT modules where the module and argspec are being updated to add these states before the underlying code support has been provided.)

2023-04-12 06:52 UTC, kannankvs commented
Changes related to "replaced" and "overridden" in plugins directory are not required and hence removed them now. They should be synced from PR221

2023-04-20 06:53 UTC, kerry-meyer commented on plugins/modules/sonic_l2_interfaces.py
Alternatively, this PR will have to wait until after PR https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/221 is merged.

2023-04-21 17:29 UTC, kannankvs commented
@kerry-meyer : I removed code for testing replaced and overridden. When I remove UT for replaced and overridden, the coverage percentage decreases below 70. Hence, I added few new combinations and improved the coverage above 70% now. Please review and merge.

2023-04-21 19:41 UTC, kerry-meyer commented on plugins/modules/sonic_l2_interfaces.py
Thanks for making the additional changes.

2023-04-24 20:38 UTC, kerry-meyer approved these changes

2023-04-24 20:38 UTC, merged