unit testing code for vrfs module added
ansible-collections/dellemc.enterprise_sonic pull request #216
Opened 2023-04-03 13:45 UTC by kannankvs

##### SUMMARY
unit testing code for vrfs module added

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
vrfs module unit testing

2023-04-03 22:16 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_vrfs.yaml
Please fix the whitespace errors in this file. They are causing Ansible sanity test failures.

2023-04-03 22:17 UTC, kerry-meyer requested changes
Please fix the whitespace errors in the tests/unit/modules/network/sonic/fixtures/sonic_vrfs.yaml file. They are causing Ansible sanity test failures.

2023-04-04 10:30 UTC, kannankvs commented
An issue [194] (https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/194)  is observed in VRF module. UT will succeed only when the issue is resolved. Need to wait until the issue is resolved.

2023-04-07 11:05 UTC, kannankvs commented on tests/unit/modules/network/sonic/fixtures/sonic_vrfs.yaml
Addressed as suggested.

2023-04-25 06:27 UTC, kerry-meyer approved these changes

2023-04-25 06:27 UTC, merged