Unit testing code for modules/sonic_config.py added
ansible-collections/dellemc.enterprise_sonic pull request #220
Opened 2023-04-04 11:41 UTC by kannankvs

##### SUMMARY
Unit testing code for modules/sonic_config.py added

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
sonic_config Unit Testing

2023-04-12 04:14 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_config.yaml
> +    commands: ['snmp-server community public group ro']
There is no "commands" argument defined for the sonic_config module. What is the purpose of this line and test?

2023-04-26 04:53 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_config.yaml
> +    commands: ['snmp-server community public group ro']
Okay. In looking at the module definition, I see that "commands" is an alias for the "lines" argument.

I will resolve this issue.

2023-04-26 05:09 UTC, kerry-meyer requested changes
These changes provide useful testing and they look good. I have posted a request to clean up the saved configuration as an additional section of the test.

2023-04-28 11:53 UTC, kannankvs commented on tests/unit/modules/network/sonic/fixtures/sonic_config.yaml
> +    - write memory
@kerry-meyer : There is no need of that. Whatever is passed in "commands" is passed asis to the device. Even if we give "no" form of command, that also goes to device asis. Even if we pass any junk values inside commands, it  goes to device asis.

2023-04-28 16:57 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_config.yaml
> +    - write memory
I realize now that the receiving side is mocked and nothing actually goes to the device. I will mark this issue "Resolved" and Approve and merge the PR.

2023-04-28 16:57 UTC, kerry-meyer approved these changes

2023-04-28 16:57 UTC, merged