Add release fragments
ansible-collections/dellemc.enterprise_sonic pull request #232
Opened 2023-04-11 17:40 UTC by mingjunzhang2019

SUMMARY
This is to add release fragments.

ISSUE TYPE
- Docs Pull Request

2023-04-19 23:10 UTC, kerry-meyer commented on changelogs/fragments/111-logging-resource-module.yaml
This fragment is not required. Because it is neither a minor nor major change, there is no good category for it, so it would be best to delete this from the change set.

REF:

https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to 

[Creating changelog fragments](https://docs.ansible.com/ansible/devel/community/development_process.html#id11)
Changelogs help users and developers keep up with changes to ansible-core and Ansible collections. Ansible and many collections build changelogs for each release from fragments. For ansible-core and collections using this model, you must add a changelog fragment to any PR that changes functionality or fixes a bug.
You do not need a changelog fragment for PRs that:
•	add new modules and plugins, because Ansible tooling does that automatically;       <<<<
•	contain only documentation changes.
[Creating a changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#id12)
PRs which add a new module or plugin do not necessarily need a changelog fragment.
major_changes
Major changes to ansible-core or a collection. SHOULD NOT include individual module or plugin changes.   <<<

2023-04-19 23:21 UTC, kerry-meyer requested changes
The formatting and structure of these fragments looks fine.

I have posted comments regarding fragments for new resource modules and using the "major_changes" designation for changes to a single resource module. (Even though these may actually be major changes, the Ansible changelog fragment definition restricts "major_changes" to changes that are made in or affect multiple modules.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/118-add-ntp-prefer-attribute.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/128-add-several-attributes-to-interface-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/132-port-group-resource-module.yaml
This fragment isn't needed. See the related comment regarding new resource modules.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/140-ip-neighbor-global-resource-module.yaml
This fragment isn't needed. See the related comment regarding new resource modules.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/151-replaced-overridden-for-ntp-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/156-replaced-overridden-for-vrfs-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/159-replaced-overridden-for-system-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/196-replaced-overridden-for-lag-interface-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/217-replaced-overridden-for-vlans-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/227-replaced-overridden-for-port-group-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/235-replaced-overridden-for-tacacs-server-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-19 23:21 UTC, kerry-meyer commented on changelogs/fragments/239-replaced-overridden-for-radius-server-resource-module.yaml
If this is only in a single resource module, it should be a "minor" change.

2023-04-20 16:14 UTC, mingjunzhang2019 commented on changelogs/fragments/111-logging-resource-module.yaml
Removed the fragment.

2023-04-20 16:15 UTC, mingjunzhang2019 commented on changelogs/fragments/118-add-ntp-prefer-attribute.yaml
Changed to "minor"

2023-04-20 16:15 UTC, mingjunzhang2019 commented on changelogs/fragments/132-port-group-resource-module.yaml
Removed the fragment.

2023-04-20 16:16 UTC, mingjunzhang2019 commented on changelogs/fragments/140-ip-neighbor-global-resource-module.yaml
Removed the fragment.

2023-04-20 16:16 UTC, mingjunzhang2019 commented on changelogs/fragments/151-replaced-overridden-for-ntp-resource-module.yaml
Changed to "minor"

2023-04-20 16:16 UTC, mingjunzhang2019 commented on changelogs/fragments/196-replaced-overridden-for-lag-interface-resource-module.yaml
Changed to "minor"

2023-04-20 16:16 UTC, mingjunzhang2019 commented on changelogs/fragments/227-replaced-overridden-for-port-group-resource-module.yaml
Changed to "minor"

2023-04-20 16:16 UTC, mingjunzhang2019 commented on changelogs/fragments/239-replaced-overridden-for-radius-server-resource-module.yaml
Changed to "minor"

2023-04-20 16:39 UTC, kerry-meyer approved these changes
Thank you for creating this fragment files and for doing the follow-on changes.

Approved.

2023-04-20 16:53 UTC, kerry-meyer requested changes
Sorry for this additional request:

After approving, I noticed that there are two failing sanity tests. 

Please look into these and post your findings as a comment on this PR.

2023-04-26 04:51 UTC, merged