Add diff and check modes support for NTP module
ansible-collections/dellemc.enterprise_sonic pull request #281
Opened 2023-07-18 19:35 UTC by mingjunzhang2019

SUMMARY
This is to add diff and check modes support for NTP module.

GitHub Issues
N/A

ISSUE TYPE
- Feature Pull Request

COMPONENT NAME
sonic_ntp

OUTPUT
- regression test log: 
[regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12088333/regression_test.log)
- regression test result: 
[regression-2023-07-18-10-46-56.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12088336/regression-2023-07-18-10-46-56.html.pdf)
- unit test script:
[ntp.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12088337/ntp.txt)
- unit test with --diff option log:
[ut_diff.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12088340/ut_diff.log)
- unit test with --diff and --check options log:
[ut_diff_check.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12088345/ut_diff_check.log)

Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

How Has This Been Tested?
Tested with real SONIC system. Did regression and unit test with test script.

2023-07-26 23:21 UTC, kerry-meyer requested changes
The main part of the change set looks good.

Thanks for doing the enhancements for replaced and overridden states in the ntp module while you were doing the other changes.

I have posted a few comments requesting minor changes, mostly for readability.

2023-07-27 22:58 UTC, mingjunzhang2019 commented on changelogs/fragments/281-playbook-check-diff-modes-for-ntp-module.yaml
> +  - Playbook check and diff modes support for sonic_ntp module (https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/281).
Done. Thanks.

2023-07-27 22:58 UTC, mingjunzhang2019 commented on plugins/module_utils/network/sonic/config/ntp/ntp.py
> +                requests.extend(add_requests)
Great finding. Thanks!

2023-07-27 22:58 UTC, mingjunzhang2019 commented on plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
> +def __DELETE_LEAFS_OR_CONFIG_IF_NO_NONE_KEY_LEAF(key_set, command, exist_conf):
Done Thanks!

2023-07-28 22:57 UTC, kerry-meyer commented on changelogs/fragments/281-playbook-check-diff-modes-for-ntp-module.yaml
> +  - Playbook check and diff modes support for sonic_ntp module (https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/281).
Verified. Thanks.

2023-07-28 22:57 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/ntp/ntp.py
> +                requests.extend(add_requests)
Verified.

2023-07-28 22:59 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/utils/formatted_diff_utils.py
> +def __DELETE_LEAFS_OR_CONFIG_IF_NO_NONE_KEY_LEAF(key_set, command, exist_conf):
Thanks for adding the headers.

2023-07-28 23:01 UTC, kerry-meyer approved these changes
Thanks for making the additional requested changes.

Approved.

2023-07-28 23:01 UTC, merged