Add Enterprise SONiC "dhcp_snooping" resource module
ansible-collections/dellemc.enterprise_sonic pull request #295
Opened 2023-09-06 16:38 UTC by simon-nathans

SUMMARY

- Add Enterprise SONiC 'dhcp_snooping' resource module:
  - Provide data definitions in 'argspec'.
  - Implement 'facts' to gather facts for the module.
  - Implement 'config' to apply configurations for merged and deleted states.
- Define regression test cases to verify correct functionality of dhcp_snooping resource module.

ISSUE TYPE

- New Module Pull Request

COMPONENT NAME

- sonic_dhcp_snooping

ADDITIONAL INFORMATION
Test Results

- Regression test HTML report:
[dhcp_snooping_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12540326/dhcp_snooping_regression_report.pdf)

- Regression test detailed log:
[dhcp_snooping_regression_terminal_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12540329/dhcp_snooping_regression_terminal_output.txt)

- Show running config and respective facts gathered:
[show_running_get_facts_output.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12540334/show_running_get_facts_output.txt)

2023-09-15 10:22 UTC, ArunSaravananBalachandran requested changes

2023-09-20 20:21 UTC, simon-nathans commented on plugins/modules/sonic_dhcp_snooping.py
> +                required: true
Please let me know the reason for this change. Changing the model at this stage takes some time: modifying the argspec, facts, and config code, updating the documentation and examples in both repositories, rewriting tests, etc. Consequently I'm not sure I can be the one to implement this change due to time commitments for my new team.

2023-09-22 00:02 UTC, kerry-meyer commented on plugins/modules/sonic_dhcp_snooping.py
> +version_added: 1.0.0
Please set the version to 2.3.0

2023-11-29 18:55 UTC, closed without merging

2023-11-29 18:55 UTC, jeff-yin commented
Closing in favor of https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/305