Vlans and interfaces resource modules check and diff modes support
ansible-collections/dellemc.enterprise_sonic pull request #301
Opened 2023-10-05 18:13 UTC by mingjunzhang2019

##### SUMMARY

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
| |

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- Test Pull Request

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below 

OUTPUT
- vlans regression test result: 
[regression-2023-10-05-09-42-34.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821687/regression-2023-10-05-09-42-34.html.pdf)
- vlans regression test log: 
[vlans_regression_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821689/vlans_regression_test.log)
- vlans unit test script: 
[vlans.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821693/vlans.txt)
- vlan unut test log: 
[vlans_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821694/vlans_unit_test.log)
- interfaces regression test result: 
[regression-2023-10-04-13-51-39.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821707/regression-2023-10-04-13-51-39.html.pdf)
- interfaces regression test log: 
[Uploading interfaces_regression_test.log…]()
- interfaces unit test script: 
[interfaces.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821750/interfaces.txt)
- interfaces unit test log: 
[interfaces_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/12821752/interfaces_unit_test.log)

Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

How Has This Been Tested?

run regression tests and unit tests.

2023-10-27 23:35 UTC, kerry-meyer requested changes
I am posting two comments (change requests), but am only requesting that one of them be made before merging this PR. The other one is retained in this PR for now, so it is available for reference in subsequent follow-up PRs needed soon for the "interfaces" resource module.

The change I am requesting now is just to add back a single instruction that is currently deleted in this change set when reading the currently configured interface speed.

Please let me know if there is a reason not to make the requested change.

2023-10-28 01:28 UTC, mingjunzhang2019 commented on plugins/module_utils/network/sonic/config/interfaces/interfaces.py
> +        intf_speed = 'SPEED_DEFAULT'
Done. TThanks.

2023-10-29 20:27 UTC, kerry-meyer requested changes
Thank you for making the requested change.

There are a few sanity errors that need to be fixed. (These weren't present in the previously posted version of this PR.) For the code coverage failures, it looks like two minor changes are needed in the UT "fixtures" file. The other two sanity failures can be eliminated by re-synching your fork and this PR branch to pick up the fix you recently provided to add a new Ansible core "ignore" version to the list of ignored module documentation checks for the non-existent "module" file corresponding to the enterprise_sonic "plugins/action/sonic.py" file. This fix was part of the change set for "Check and diff modes support for l2- and lag-interfaces modules" (https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/303).

2023-10-30 17:55 UTC, mingjunzhang2019 commented
Fixed sanity error. Thanks.

2023-10-30 18:52 UTC, kerry-meyer requested changes
The code coverage (UT) failures were fixed by your most recent push today, but please also resync your fork and branch to verify that the other sanity failures (for "CI / sanity / py3.10 / ubuntu-latest / devel" and "CI / sanity / py3.11 / ubuntu-latest / devel") are fixed by the changes that were merged for "Check and diff modes support for l2- and lag-interfaces modules" (https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/303)".

2023-10-30 20:26 UTC, mingjunzhang2019 commented
Done the merge with main and fixed those sanity errors.

2023-10-30 23:40 UTC, kerry-meyer approved these changes
Thanks for doing the re-sync to verify the sanity results for this change set.

I see that all checks are passing now.

Approved.

2023-10-30 23:40 UTC, merged