Diff and check modes support for acl_interfaces l2_acls and l3_acls modules
ansible-collections/dellemc.enterprise_sonic pull request #306
Opened 2023-10-30 17:10 UTC by mingjunzhang2019

SUMMARY
This is to add playbook diff and check modes support for sonic_acl_interfaces, sonic_l2_acls and sonic_l3_acls resource modules.

GitHub Issues
N?A

ISSUE TYPE
- Feature Pull Request

COMPONENT NAME
sonic_interfaces, sonic_l2_acls, sonic_l3_acls

OUTPUT
- acl_interfaces regression result: 
[acl_interfaces_regression-2023-10-27-12-12-00.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207843/acl_interfaces_regression-2023-10-27-12-12-00.html.pdf)
- acl_interfaces regression log: 
[acl_interfaces_regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207845/acl_interfaces_regression.log)
- acl_interfaces unit test script:
[acl_interfaces.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207849/acl_interfaces.txt)
- acl_interfaces unit test log: 
[acl_interfaces_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207851/acl_interfaces_unit_test.log)

- l2_acls regression result: 
[l2_acls_regression-2023-10-23-11-52-53.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207859/l2_acls_regression-2023-10-23-11-52-53.html.pdf)
- l2_acls regression log: 
[l2_acls_regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207861/l2_acls_regression.log)
- l2_acls unit test script: 
[l2_acls.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207865/l2_acls.txt)
- l2_acls unit test log: 
[l2_acls_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207868/l2_acls_unit_test.log)

- l3_acls_regression result: 
[l3_acls_regression-2023-10-25-14-39-28.html.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207875/l3_acls_regression-2023-10-25-14-39-28.html.pdf)
- l3_acls regression log: 
[l3_acls_regression.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207880/l3_acls_regression.log)
- l3_acls unit test script: 
[l3_acls.txt](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207883/l3_acls.txt)
- l3_acls unit test log: 
[l3_acls_unit_test.log](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/13207885/l3_acls_unit_test.log)

Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

How Has This Been Tested?
Run regressions and unit tests.

2023-11-22 18:04 UTC, ArunSaravananBalachandran requested changes

2023-11-22 21:55 UTC, mingjunzhang2019 commented on plugins/module_utils/network/sonic/config/acl_interfaces/acl_interfaces.py
> +            result['after(generated)'] = new_config
Added the documents. Thanks.

2023-11-22 21:57 UTC, mingjunzhang2019 commented on plugins/module_utils/network/sonic/config/acl_interfaces/acl_interfaces.py
> +            result['config_diff'] = get_formatted_config_diff(old_config,
Will do in a seperated PR to see if unified_diff provides better informative data.

2023-11-23 06:02 UTC, ArunSaravananBalachandran requested changes

2023-11-23 06:02 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/acl_interfaces/acl_interfaces.py
> +            result['config_diff'] = get_formatted_config_diff(old_config,
Thanks. Since, the changes for diff generation are to be added in a separate PR closing this comment.

2023-11-23 06:02 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_l2_acls.py
Please add a note on the check_mode support after the existing module description.

2023-11-23 06:02 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_l3_acls.py
Please add a note on the check_mode support after the existing module description.

2023-11-23 06:02 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_l2_acls.py
> +  returned: when changed
```suggestion
  returned: when C(check_mode)
```

2023-11-23 06:02 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_l3_acls.py
> +  returned: when changed
```suggestion
  returned: when C(check_mode)
```

2023-11-27 17:52 UTC, mingjunzhang2019 commented on plugins/modules/sonic_l3_acls.py
> +  returned: when changed
Done Thanks!

2023-11-27 17:52 UTC, mingjunzhang2019 commented on plugins/modules/sonic_l3_acls.py
Done Thanks!

2023-11-27 17:52 UTC, mingjunzhang2019 commented on plugins/modules/sonic_l2_acls.py
Done Thanks!

2023-11-27 17:52 UTC, mingjunzhang2019 commented on plugins/modules/sonic_acl_interfaces.py
> +  returned: when changed
Done Thanks!

2023-11-27 17:53 UTC, mingjunzhang2019 commented on plugins/modules/sonic_acl_interfaces.py
Done Thanks!

2023-11-28 21:01 UTC, kerry-meyer requested changes
Code changes, review comment resolution, and posted test results all look good.

Thank you for providing these changes.

Please provide updated regression test results for the current version of the change set to confirm that regression results remain fine after the PR branch re-sync done last week.

2023-11-28 22:43 UTC, kerry-meyer approved these changes
Thank you for posting the updated regression test results.

Approved.

2023-11-28 22:43 UTC, merged