Add Dell Enterprise SONiC 'pim_interfaces' module
ansible-collections/dellemc.enterprise_sonic pull request #369
Opened 2024-04-24 17:08 UTC by ArunSaravananBalachandran

##### SUMMARY

- Add Enterprise SONiC 'pim_interfaces' resource module:
  - Provide data definitions in 'argspec'.
  - Implement 'facts' to gather facts for the module.
  - Implement 'config' to apply configurations for merged, deleted, replaced and overridden states.
  - Implement support for 'check' and 'diff' modes.
- Define regression test cases to verify correct functionality of pim_interfaces resource module.

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
| N/A |

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- sonic_pim_intefaces

##### OUTPUT

##### ADDITIONAL INFORMATION

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [ ] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Regression report: [pim_interfaces_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/15097948/pim_interfaces_regression_report.pdf)

2024-05-06 06:59 UTC, kerry-meyer requested changes
Thank you for providing this implementation of the "PIM interfaces" resource module.

The code structure and test results look good.

I have no questions or comments on the instructions in the proposed change set. I have posted only minor documentation change requests.

2024-05-06 10:29 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_interfaces.py
> +  - BFD profile need to be created earlier in the device.
Done.

2024-05-06 10:29 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_interfaces.py
> +  description: The configuration prior to the model invocation.
Done.

2024-05-06 10:30 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_interfaces.py
> +     of the parameters above.
Done.

2024-05-06 10:30 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_interfaces.py
> +     of the parameters above.
Done.

2024-05-06 10:30 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_interfaces.py
> +  description: The generated configuration model invocation.
Done.

2024-05-06 10:30 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_interfaces.py
> +     of the parameters above.
Done.

2024-05-07 00:18 UTC, kerry-meyer commented
Thanks for making the incremental changes for this change set.

The revised code looks good, and the posted test results look good.

Thank you for implementing the "PIM Interfaces" resource module.

To proceed with approval and merging of this PR, please resolve the merge conflicts and notify me. I will Approve and merge the PR after that.

2024-05-07 05:21 UTC, kerry-meyer approved these changes
Thanks for making the incremental changes for this change set and re-synching the PR branch to merge in recent changes in the common files.

The revised code looks good, and the posted test results look good.

Thank you for implementing the "PIM Interfaces" resource module.

2024-05-07 05:21 UTC, merged