Add Dell Enterprise SONiC 'pim_global' module
ansible-collections/dellemc.enterprise_sonic pull request #370
Opened 2024-04-24 17:13 UTC by ArunSaravananBalachandran

##### SUMMARY

- Add Enterprise SONiC 'pim_global' resource module:
  - Provide data definitions in 'argspec'.
  - Implement 'facts' to gather facts for the module.
  - Implement 'config' to apply configurations for merged, deleted, replaced and overridden states.
  - Implement support for 'check' and 'diff' modes.
- Define regression test cases to verify correct functionality of pim_global resource module.

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
| N/A |

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- sonic_pim_global

##### OUTPUT

##### ADDITIONAL INFORMATION

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [ ] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Regression report: [pim_global_regression_report.pdf](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/15097990/pim_global_regression_report.pdf)

2024-05-05 23:26 UTC, kerry-meyer requested changes
Thank you for providing this change set to implement the 'pim_global' resource module.

The code structure and test results look good.

I have posted a few comments regarding documentation in the 'module' file and some other comments/questions on implementation details.

There are also some merge conflicts introduced into the common/shared files by recent merges.

2024-05-06 08:14 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_global.py
> +  description: The configuration prior to the model invocation.
Done.

2024-05-06 08:14 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_global.py
> +     of the parameters above.
Done.

2024-05-06 08:14 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_global.py
> +     of the parameters above.
Done.

2024-05-06 08:14 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_pim_global.py
> +     of the parameters above.
Done.

2024-05-06 08:15 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/pim_global/pim_global.py
> +TEST_KEYS_GENERATE_CONFIG = [{'config': {'vrf_name': '', '__delete_op': __DELETE_SUBCONFIG_AND_LEAFS}}]
As suggested, have made changes to use default (__DELETE_OP_DEFAULT).

2024-05-06 08:26 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/pim_global/pim_global.py
> +                    vrf_requests.append({'path': self.pim_global_config_path['ecmp_enable'].format(vrf=vrf), 'method': DELETE})
The delete is being done to be in line with performing the same configurations over CLI.

2024-05-06 08:27 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/pim_global/pim_global.py
> +                    vrf_requests.insert(0, {'path': self.pim_global_config_path['ecmp_rebalance_enable'].format(vrf=vrf), 'method': DELETE})
The delete is being done to be in line with performing the same configurations over CLI.

2024-05-06 08:29 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/facts/pim_global/pim_global.py
> +            config['ecmp_enable'] = conf['config'].get('ecmp-enabled', False)
When 'ecmp'/'ecmp_rebalance' is not enabled (default), the data will be empty.
Hence, the enable value for them is set to 'False' if their setting is not available.

2024-05-06 08:42 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/pim_global/pim_global.py
> +                    self._module.fail_json(msg='ECMP cannot be disabled when ECMP Rebalance is enabled')
As suggested, have updated the check to handle cases for 'replaced' and 'overridden' states.

2024-05-06 19:39 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/pim_global/pim_global.py
> +                    vrf_requests.append({'path': self.pim_global_config_path['ecmp_enable'].format(vrf=vrf), 'method': DELETE})
Thank you for explaining.

Resolved.

2024-05-06 23:02 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/facts/pim_global/pim_global.py
> +            config['ecmp_enable'] = conf['config'].get('ecmp-enabled', False)
I can see why this is needed if we are matching the CLI implementation.

Resolved.

2024-05-06 23:38 UTC, kerry-meyer commented
The revised code looks good and all issues are now "Resolved".

The updated test results look good, but there is an anomaly that needs to be investigated in the posted html regression results with 'check and diff' modes. activated:

In 'check' mode, the "result['after']" dictionary should be empty, but it in the html regression results, the 'After' column is being displayed with the same content in the output as the 'After(Generated)' column (except that the dictionary members are in a different order).

The console log shows that, at execution time, the 'after' dict was, as expected, empty. This proves that the correct actions were taken during execution of the resource module for each test case.

Also, the  'After(Generated)' and 'Diff' outputs look correct.

I looked briefly at the corresponding Jinja2 and report generation files to see if there is an explanation there for the unexpected 'After' results in the test reports, but it isn't yet clear to me why this is happening.

Although I think this anomaly requires more investigation, I don't think the problem is in any way related to this change set, so I will proceed with approving and merging the change set.

If you have time, please see if you can determine a reason for the anomaly mentioned here.

2024-05-06 23:41 UTC, kerry-meyer approved these changes
The updated code an corresponding test results all look good.

Thank you very much for implementing the "PIM global" resource module.

Approved.

2024-05-06 23:42 UTC, merged