Add Dell Enterprise SONiC 'ldap' module
ansible-collections/dellemc.enterprise_sonic pull request #372
Opened 2024-05-02 16:45 UTC by santhosh-kt

##### SUMMARY

- Add Enterprise SONiC 'ldap' resource module:
  - Provide data definitions in 'argspec'.
  - Implement 'facts' to gather facts for the module.
  - Implement 'config' to apply configurations for merged, deleted, replaced and overridden states.
  - Implement support for 'check' and 'diff' modes.
- Define regression test cases to verify correct functionality of ldap resource module.

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
| |

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- sonic_ldap
##### OUTPUT

```paste below

```

##### ADDITIONAL INFORMATION

```paste below

```
[regression-2024-05-02-17-20-04.zip](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/15191305/regression-2024-05-02-17-20-04.zip)

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-05-03 07:56 UTC, santhosh-kt commented
Code coverage failed for other modules.
LDAP code coverage is successful.

2024-05-28 06:22 UTC, kerry-meyer requested changes
Thank you for providing this support for LDAP configuration.

The code structure, test cases, and test results look good.

I have posted some comments requesting changes, mostly on documentation and reductions in code or in processing time. There are also a few cases requiring modified code for full coverage.

2024-05-29 11:29 UTC, santhosh-kt commented on plugins/modules/sonic_ldap.py
> +          nss_base_passwd: password
Was intended to illustrate that existing configuration will not get affected even if it is applied again.

2024-05-31 05:59 UTC, santhosh-kt commented on plugins/modules/sonic_ldap.py
> +  description: The configuration prior to the model invocation.
Updated.

2024-05-31 05:59 UTC, santhosh-kt commented on plugins/modules/sonic_ldap.py
> +     of the parameters above.
Updated.

2024-05-31 06:00 UTC, santhosh-kt commented on plugins/modules/sonic_ldap.py
> +     of the parameters above.
Updated.

2024-05-31 06:00 UTC, santhosh-kt commented on plugins/modules/sonic_ldap.py
> +     of the parameters above.
Updated.

2024-05-31 06:00 UTC, santhosh-kt commented on plugins/modules/sonic_ldap.py
> +    :returns: the result form module invocation
Updated.

2024-05-31 06:00 UTC, santhosh-kt commented on plugins/modules/sonic_ldap.py
> +          pam_login_attribute: "globallogin"
Corrected all examples.

2024-05-31 06:00 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/facts/ldap/ldap.py
> +        config = ldap_config.get('config')
Updated.

2024-05-31 06:01 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/facts/ldap/ldap.py
> +        request = [{"path": 'data/openconfig-system:system/aaa/server-groups/server-group=LDAP/servers', "method": "GET"}]
Refactored the code so that the server details will be retrieved from the root request itself.

2024-05-31 06:01 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/facts/ldap/ldap.py
> +    def get_ldap_nss_config(self, ldap_config):
Refactored multiple functions into one generic function to handle.

2024-05-31 06:01 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +    {'attribute': {'from': '', 'to': ''}},
Removed 'to' attribute from the TEST_KEYS and TEST_KEYS_formatted_diff

2024-05-31 06:02 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +TEST_KEYS_formatted_diff = [
Used other __delete_op constants appropriately. 
Uploaded check_mode regression html as well

2024-05-31 06:03 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +        new_config = existing_ldap_facts
Instead of old_config, new_config is reconfigured.
Refactored.

2024-05-31 06:03 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +        changed_ldap_facts = self.get_ldap_facts()
Refactored into else part of check_mode check

2024-05-31 06:03 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +        for cmd in diff1:
Refactored overridden and replaced logics

2024-05-31 06:03 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +                        if None not in (conf.get(attr), have_conf.get(attr)):
Updated.

2024-05-31 06:04 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +        validate_config(self._module.argument_spec, {'config': updated_config_list})
validate_config being called before changes.
Reseated this function call at the end of the validate_and_normalize_config function

2024-06-11 01:03 UTC, kerry-meyer requested changes
Thank you for making the changes to address the previous set of comments.

I have posted a few follow-up comments. Most of them should require only isolated single-line changes with no changes to code flow logic.

Please also post results showing output in 'check' mode for the 'merged' and 'deleted' cases that you feel should be verified. (e.g. merge/delete at least one attribute for each of the following attribute categories: top level, item from the 'servers' list, attribute from a server, a 'generic' map and 'generic' map attribute, a 'map_remote_groups_to_sonic_roles' map and attribute).

2024-06-12 15:57 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +            result.pop('after', None)
Removed.

2024-06-12 15:57 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +    def _state_replaced(self, want, have):
Refactored into one function

2024-06-12 15:57 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +                    cfg[attr] = config[attr]
Added a failed call

2024-06-12 15:58 UTC, santhosh-kt commented on plugins/module_utils/network/sonic/config/ldap/ldap.py
> +                        if have_conf.get(attr) is not None:
Added the value check on attributes, source_interface and server_attributes.

2024-06-13 19:31 UTC, kerry-meyer approved these changes
Thank you for making the final set of incremental changes.

All of the code in the current proposed change set and the corresponding test results looks good.

Thank you very much for providing the LDAP resource module for the enterprise_sonic resource module collection.

Approved.

2024-06-13 19:31 UTC, merged