Update AAA module
ansible-collections/dellemc.enterprise_sonic pull request #382
Opened 2024-05-16 21:18 UTC by stalabi1

##### SUMMARY

I updated the AAA module authentication implementation to support ordered authentication. This is a breaking change that was reverted in #269. 

Please see [model PR](https://github.com/ansible-network/resource_module_models/pull/209).

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

sonic_aaa

##### OUTPUT

[regression-2024-07-23-14-56-54.html.pdf](https://github.com/user-attachments/files/16354640/regression-2024-07-23-14-56-54.html.pdf)
[diff_output.log](https://github.com/user-attachments/files/15978829/diff_output.log)
[merge_aaa.yaml.txt](https://github.com/user-attachments/files/15978972/merge_aaa.yaml.txt)
[check_merged.log](https://github.com/user-attachments/files/15978980/check_merged.log)
[delete_aaa_yaml.txt](https://github.com/user-attachments/files/15978984/delete_aaa_yaml.txt)
[check_delete.log](https://github.com/user-attachments/files/15979020/check_delete.log)
[facts_gathering.log](https://github.com/user-attachments/files/15979027/facts_gathering.log)

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

2024-06-10 22:09 UTC, kerry-meyer approved these changes
The proposed changes and corresponding test results look good.

Thank you for re-posting these changes to bring the AAA module into compliance with the intended SONiC functionality for AAA.

Approved.

2024-06-12 21:25 UTC, kerry-meyer commented on plugins/modules/sonic_aaa.py
> +                version_added: 2.5.0
Please make this 3.0.0 (because it is part of a "breaking" change).

2024-06-24 19:56 UTC, kerry-meyer requested changes
I haven't finished reviewing this PR, but I'm posting my current comments so they can be addressed in parallel with adding support for the new AAA 'name-service' attributes.

2024-06-25 05:39 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
> +            if cfg_authentication:
You are correct that I overlooked the initial check for absence of any AAA configuration and the default return of 'want'. That covers the first question of my comment.

But the handling for empty configuration **subsets** is still needed: Even if there is configuration for 'authorization', there may not be any for 'authentication' (and vice versa). Both of these cases would be covered by initializing cfg_dict to 'want'.

2024-06-25 05:46 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
> +        new_conf['console_auth_local'] = False
If a default value is specified for console_auth_local, the current 'derive_authentication_delete' handling for this attribute is correct, but if the 'default' is removed, as suggested in my comment in the 'argspec' file, the handling here should be changed accordingly.

2024-07-23 20:38 UTC, mingjunzhang2019 commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
> +            config_dict['name_service'] = cfg_name_service
If the above cfg_*** are None or {}, the replace should not happen.

2024-07-23 20:40 UTC, mingjunzhang2019 commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
> +            is_delete_all = replaced_config == have
There are many lists in args like have, want and replaced_config, if the lists are not sorted, The comparison "==" does nor work properly???

2024-07-23 20:42 UTC, mingjunzhang2019 commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
> +            is_delete_all = True
The comment on line#209: see above comment for _state_replaced.

2024-07-24 16:25 UTC, mingjunzhang2019 approved these changes

2024-07-25 21:17 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/argspec/aaa/aaa.py
> +                        'console_auth_local': {'default': False, 'type': 'bool'},
Verified.

2024-07-25 21:19 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/facts/aaa/aaa.py
> +from __future__ import (absolute_import, division, print_function)
Verified

2024-07-25 21:19 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/facts/aaa/aaa.py
> +        """ Populate the facts for qos_pfc
Verified.

2024-07-25 22:13 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/facts/aaa/aaa.py
> +        # Authoriation configuration handling
Verified

2024-07-25 22:13 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/facts/aaa/aaa.py
> +        """Retrive OC configuration from device"""
Verified.

2024-07-25 22:27 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
> +                if failthrough and failthrough != cfg_failthrough:
Verified.

2024-07-25 22:28 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
> +        new_conf['console_auth_local'] = False
Verified.

2024-08-19 23:45 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
> +            if cfg_authentication:
I have checked the current handling for the cases mentioned in this issue. The current handling looks fine and fully addresses the requirements for these cases.

Resolved.

2024-08-20 00:25 UTC, kerry-meyer approved these changes
Now that the 2.x branch sync is done, we can proceed with merging this revised AAA resource module.

I have finished checking the contents of this PR. All proposed changes and corresponding test results look good.

Thank you for providing this revised version of the AAA resource module to better fit the intent and current operation of the AAA feature in SONiC.

Approved.

2024-08-20 00:25 UTC, merged