OSPFv2_interfaces - Add Enterprise SONiC resource module
ansible-collections/dellemc.enterprise_sonic pull request #385
Opened 2024-05-29 09:34 UTC by santhosh-kt

##### SUMMARY

- Add Enterprise SONiC 'OSPFv2_interfaces' resource module:
    - Provide data definitions in 'argspec'.
    - Implement 'facts' to gather facts for the module.
    - Implement 'config' to apply configurations for `merged` , `deleted`, `overridden` and `replaced` states.
- Define regression test cases to verify correct functionality of ospfv2_interfaces resource module.
- Define unit test cases to verify correct functionality of ospfv2_interfaces resource module.

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
| |

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- sonic_ospfv2_interfaces

##### OUTPUT

[regression-2024-05-29-14-53-57.zip](https://github.com/ansible-collections/dellemc.enterprise_sonic/files/15482241/regression-2024-05-29-14-53-57.zip)

##### ADDITIONAL INFORMATION

```paste below

```

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-06-03 07:11 UTC, ArunSaravananBalachandran requested changes

2024-06-03 07:11 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_ospfv2_interfaces.py
> +                  - Indicates whether the password is encrypted text.
```suggestion
          message_digest_key:
            description:
              - Configure OSPFv2 message digest keys and password.
              - Uses MD5 algorithm.
            type: list
            elements: dict
            suboptions:
              key_id:
                description:
                  - Specifies the OSPFv2 message digest key ID (1 to 255).
                type: int
                required: True
              md5key:
                description:
                  - Specifies the OSPFv2 message digest password.
                  - Plain text password i.e. password with I(encrypted=false) will be stored in encrypted format in running-config, so idempotency will
                   not be maintained and hence the task output will always be I(changed=true).
                type: str
              encrypted:
                description:
                  - Indicates whether the password is in encrypted format.
```

2024-06-03 07:11 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/facts/ospfv2_interfaces/ospfv2_interfaces.py
> +                                        self.update_dict(attr, 'dead_interval', config.get('dead-interval'))
Could be simplified as:
```suggestion
                                    if config.get('dead-interval-minimal'):
                                        self.update_dict(attr, 'hello_multiplier', config.get('hello-multiplier'))
                                    else:
                                        self.update_dict(attr, 'dead_interval', config.get('dead-interval'))
```

2024-06-03 07:11 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/facts/ospfv2_interfaces/ospfv2_interfaces.py
> +                                    if addr != '0.0.0.0':
Please use a variable for the default interface OSPF address.

2024-07-02 21:52 UTC, jeff-yin commented
@ArunSaravananBalachandran  please review the latest changes, resolve any open comments that you feel have been adequately addressed, and review/approve this PR.

2024-07-03 10:31 UTC, ArunSaravananBalachandran requested changes

2024-07-26 07:06 UTC, ArunSaravananBalachandran requested changes

2024-07-26 07:06 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_ospfv2_interfaces.py
> +version_added: '3.0.0'
```suggestion
version_added: '2.5.0'
```

2024-08-02 14:44 UTC, ArunSaravananBalachandran requested changes

2024-08-02 14:44 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/ospfv2_interfaces/ospfv2_interfaces.py
> +                                        if bfd_attr not in have_conf:
```suggestion
                                        if bfd_attr not in have_conf[attr]:
```

2024-08-05 10:52 UTC, ArunSaravananBalachandran approved these changes

2024-08-06 23:10 UTC, kerry-meyer approved these changes
The posted change set and corresponding test results look good.

Thank you very much for implementing the OSPFv2 "interfaces" resource module for the enterprise_sonic Ansible collection.

Approved.

2024-08-06 23:11 UTC, merged