Auditd feature support.
ansible-collections/dellemc.enterprise_sonic pull request #405
Opened 2024-06-24 21:09 UTC by bhaveshdell

Configure audit rules.

##### SUMMARY
Auditd feature support.

##### GitHub Issues
NA

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
sonic_system

##### OUTPUT

```paste below

```

##### Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [ ] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

2024-07-01 20:31 UTC, xhan-dell commented
Looks like regression print to pdf cut off the last columns. May need to change print settings to landscape mode and bigger paper size. Could you repost one that has the after column?
![image](https://github.com/ansible-collections/dellemc.enterprise_sonic/assets/143125816/a92f9247-8ecf-4013-97d9-96762858e1bc)

2024-07-01 23:00 UTC, bhaveshdell commented
@xhan-dell regression output reposted.

2024-07-02 00:09 UTC, xhan-dell requested changes
changes look good, few requests. Found it a bit weird the module itself without changes returns null values in facts

2024-07-02 21:00 UTC, xhan-dell commented on tests/regression/roles/sonic_system/defaults/main.yml
> +      audit_rules: BASIC
this one is more the module rather than the changes here

2024-07-10 19:24 UTC, bhaveshdell commented on plugins/module_utils/network/sonic/argspec/system/system.py
> +                    'choices': ['BASIC', 'DETAIL', 'CUSTOM', 'NONE'],
Add NONE to module spec,

2024-07-10 19:24 UTC, bhaveshdell commented on plugins/module_utils/network/sonic/config/system/system.py
> +            if audit_rules is not None and audit_rules != "NONE":
Add NONE to module spec,

2024-07-10 19:24 UTC, bhaveshdell commented on plugins/module_utils/network/sonic/config/system/system.py
> +        new_conf['audit_rules'] = 'NONE'
Add NONE to module spec,

2024-07-11 21:54 UTC, bhaveshdell commented on tests/regression/roles/sonic_system/defaults/main.yml
> +      audit_rules: BASIC
Added testcase for NONE, The CUSTOM type has dependencies on other config.

2024-07-11 22:40 UTC, xhan-dell commented on tests/regression/roles/sonic_system/defaults/main.yml
> +      audit_rules: BASIC
what is the config it is dependent on?

2024-07-16 23:21 UTC, xhan-dell commented on tests/regression/roles/sonic_system/defaults/main.yml
> +      audit_rules: BASIC
After conversation, I will resolve this since it seems difficult to add to regression tests

2024-07-18 00:11 UTC, xhan-dell approved these changes

2024-08-04 00:01 UTC, kerry-meyer requested changes
The proposed code changes and corresponding test results look good.

My only requested change is to fix an incorrect 'after' display for an "EXAMPLE" case in the "module" file.

Please also resolve the merge conflicts and sanity failures.

2024-08-09 17:33 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/system/system.py
>              requests.append(request)
The auditd added instructions overwrote the "requests.append(request)" for "load_share_hash_algo".

Here is a recommended fix for that:

```suggestion
            requests.append(request)
        audit_rules_path = 'data/openconfig-system:system/openconfig-system-ext:auditd-system/config/audit-rules'
        audit_rules_payload = self.build_create_audit_rules_payload(commands)
        if audit_rules_payload:
            request = {'path': audit_rules_path, 'method': method, 'data': audit_rules_payload}
            requests.append(request)
```

2024-08-09 17:41 UTC, kerry-meyer commented on plugins/modules/sonic_system.py
> +#auditd-system rules basic
I see that this has been fixed.

Resolved.

2024-08-09 20:15 UTC, kerry-meyer approved these changes
All the current proposed code changes and corresponding test results look good.

Thank you for providing the "auditd" support for the enterprise_sonic Ansible resource module collection.

Approved.

2024-08-09 20:15 UTC, merged