Remote Audit LOG
ansible-collections/dellemc.enterprise_sonic pull request #424
Opened 2024-08-08 04:21 UTC by arulkumar9690

SUMMARY
Logging - Module Enhancement

ISSUE TYPE

Added "audit" message-type option

COMPONENT NAME
sonic_logging

ADDITIONAL INFORMATION

Regression test HTML report:
[Remote_audit_LOG.pdf](https://github.com/user-attachments/files/16537600/Remote_audit_LOG.pdf)

2024-09-17 23:48 UTC, kerry-meyer commented on plugins/modules/sonic_logging.py
There is a merge conflict for this file. (The "deleted" example has a merge conflict with the changes made for adding TLS logging with https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/423.)

Please resolve this conflict.

2024-09-17 23:57 UTC, kerry-meyer requested changes
The proposed changes and test results look good.

Before merging this PR, there is a conflict that needs to be resolved:

There is a merge conflict for the "module" file. (The "deleted" example has a merge conflict with the changes made for adding TLS logging with https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/423.)

Please resolve this conflict to proceed with approval and merging.

**********
While you are doing the conflict resolution, please also correct the text for the "overridden" example to use the correct state ("override" instead of "replace" at line 184).

2024-09-18 05:13 UTC, arulkumar9690 commented on plugins/modules/sonic_logging.py
Resolved the merge conflicts.

2024-09-18 05:35 UTC, kerry-meyer approved these changes
All proposed changes and corresponding test results look good.

Approved.

2024-09-18 05:36 UTC, merged