bgp_communities - Update 'aann' option, Fix issues in merged state
ansible-collections/dellemc.enterprise_sonic pull request #440
Opened 2024-08-22 10:27 UTC by ArunSaravananBalachandran

##### SUMMARY

Incorporate the below changes in sonic_bgp_communites module:
- Change 'aann' as a suboption of 'members' and update it to support 'list of strings'. 
- Fix issue in merged state for standard community-list when community options are specified as 'False'.
- Update default value behavior for 'type' and 'match' to be in-line with 'permit'.
- Update documentation, UT and regression test cases.

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
| N/A |

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- sonic_bgp_communities

##### OUTPUT

##### ADDITIONAL INFORMATION

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Regression report: [bgp_communities_regression_report-2024-08-22-15-44-53.pdf](https://github.com/user-attachments/files/16709153/bgp_communities_regression_report-2024-08-22-15-44-53.pdf)

2024-09-25 23:58 UTC, kerry-meyer requested changes
Thank you for providing these changes to provide more complete support in the enterprise_sonic Ansible resource module collection for the BGP Communities functionality currently implemented in SONiC.

The proposed changes, updated test cases, and test results look good.

I am posting only a few minor comments/questions.

2024-09-26 05:55 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
> +                for attr in ('type', 'permit', 'match'):
'want' is updated in `validate_and_normalize_config`, but 'diff' will not have the required fields is they are the same in 'want' and 'have'. Hence, they are being updated here.

Have added a comment on the same.

2024-09-26 05:57 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
> +                    if value is None:
Yes, empty options for 'regex' and 'aann' are supported (not members, due to the default ansible behavior).
Have updated the comment to specify the supported behavior.

2024-09-26 05:57 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
> +                                if cmd.get(attr) and item.get(attr) and cmd[attr] == item[attr]:
The variable name has been updated as suggested.

2024-09-26 05:58 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_bgp_communities.py
> +        - Default value while adding a new community-list is C(standard).
As suggested, have updated the description for similar options (match, permit).

2024-09-26 06:17 UTC, kerry-meyer commented on plugins/modules/sonic_bgp_communities.py
> +        - Default value while adding a new community-list is C(standard).
Thanks for making these changes.

Resolved.

2024-09-26 06:19 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
> +                    if value is None:
Thanks for clarifying this.

Resolved.

2024-09-26 06:24 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
> +                for attr in ('type', 'permit', 'match'):
Thanks for explaining and for providing the explanation in a comment for future readers and maintainers.

Resolved.

2024-09-26 06:26 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/bgp_communities/bgp_communities.py
> +                                if cmd.get(attr) and item.get(attr) and cmd[attr] == item[attr]:
Thanks for making this change.

Resolved.

2024-09-26 06:28 UTC, kerry-meyer approved these changes
Thanks for addressing the posted comments.

All current proposed code changes and comments, test cases, and test results look good.

Approved.

2024-09-26 06:28 UTC, merged