Set "interface vlanX" 'suppress_vlan_neigh' option
ansible-collections/dellemc.enterprise_sonic pull request #448
Opened 2024-09-11 22:04 UTC by aida-shumburo

##### SUMMARY
Set up the new 'suppress_vlan_neigh' option for vxlans.

##### GitHub Issues
"N/A".

| GitHub Issue # |
| -------------- |
| |

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

sonic_vxlans

##### OUTPUT

##### Ansible Report:
[suppress_vlan_neigh.pdf](https://github.com/user-attachments/files/16970848/suppress_vlan_neigh.pdf)

##### Raw Regression Test Output:

##### Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [ ] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [] I ran different ansible playbooks to test that the new 'suppress_vlan_neigh' option value is being merged, replaced, deleted, and overriden the correct way.
- [] Ran a regression test (attached above)

2024-10-01 16:55 UTC, aida-shumburo commented on plugins/modules/sonic_vxlans.py
> +        description: 'list map of vlan names with suppress on'
Changed vlan to VLAN.

2024-10-01 16:56 UTC, aida-shumburo commented on changelogs/fragments/448-set-suppress-vlan-neigh-option.yaml
> +  - sonic-vxlan - add 'suppress_vlan_neigh' option (https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/448)
Updated the capitalization of 'add'.

2024-10-01 16:58 UTC, aida-shumburo commented on tests/regression/roles/sonic_vxlan/defaults/main.yml
Added.

2024-10-01 16:58 UTC, aida-shumburo commented on plugins/module_utils/network/sonic/config/vxlans/vxlans.py
> +                url = "data/sonic-vxlan:sonic-vxlan/SUPPRESS_VLAN_NEIGH"
UPdated the url.

2024-10-01 16:59 UTC, aida-shumburo commented on plugins/module_utils/network/sonic/facts/vxlans/vxlans.py
> +            matched_suppres_vn = None
I changed the spelling for the variable.

2024-10-03 14:52 UTC, aida-shumburo commented on changelogs/fragments/448-set-suppress-vlan-neigh-option.yaml
> +  - sonic-vxlan - Add 'suppress_vlan_neigh' option (https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/448)
Made the suggested change.

2024-10-03 14:52 UTC, aida-shumburo commented on plugins/module_utils/network/sonic/config/vxlans/vxlans.py
> +# © Copyright 20204 Dell Inc. or its subsidiaries. All Rights Reserved
Made the suggested change.

2024-10-03 14:52 UTC, aida-shumburo commented on plugins/module_utils/network/sonic/config/vxlans/vxlans.py
> +                    have_suppress_vlan_neigh_count -= len(temp_suppress_vlan_neigh_requests)
Made the suggested change.

2024-10-03 23:31 UTC, kerry-meyer commented on tests/regression/roles/sonic_vxlan/defaults/main.yml
> +          - vlan_name: Vlan6
Vlan6 was previously configured as a "suppress_vlan_neigh" Vlan in test_04.

The reason for requesting the addition of another test entry in this test was to test adding another Vlan to an existing "suppress vlan neighbor" list. This Vlan will not be visible after the diff is obtained and will not cause any action. Please specify some Vlan other than 6 or 7 here.

2024-10-03 23:31 UTC, kerry-meyer commented on tests/regression/roles/sonic_vxlan/defaults/main.yml
Although a line was added to test case 5, it specified a Vlan that was already present in the "suppress neighbor" list. Please change that line to specify a different Vlan number.

2024-10-03 23:37 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_vxlans.yaml
Removing the "dead" code in the config file has slightly increased the code coverage (by 1%,), but it is still below the baseline coverage percentage. More importantly, the main reason for requesting the additional UT cases here was to make sure the 3 cases described above work as required.

Please add those test cases. I expect this will bring the code coverage back up to or above where it is in the current baseline.

2024-10-03 23:44 UTC, kerry-meyer requested changes
Most of the issues are resolved now, but there are still a couple of test changes/enhancements needed before merging this PR.

Please let me know if you have questions on these

2024-10-03 23:44 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_vxlans.yaml
Please see the comment posted on the main comment thread for this file. (There are still 3 cases that need to be added.)

2024-10-04 22:30 UTC, kerry-meyer commented on tests/regression/roles/sonic_vxlan/defaults/main.yml
I see that this has been modified as requested. Thank you.

Resolved.

2024-10-04 23:06 UTC, kerry-meyer commented on tests/unit/modules/network/sonic/fixtures/sonic_vxlans.yaml
I see that these test cases have been added.

Thanks for these updates.

Resolved.

2024-10-04 23:09 UTC, kerry-meyer approved these changes
All current proposed changes and the corresponding test results look good.

Thank you for providing this enhancement to the functionality of the enterprise_sonic Ansible resource module collection.

Approved.

2024-10-04 23:09 UTC, merged