bgp_af - Add support for 'dup-addr-detection' commands
ansible-collections/dellemc.enterprise_sonic pull request #452
Opened 2024-09-20 11:41 UTC by ArunSaravananBalachandran

##### SUMMARY

Incorporate the below changes in 'bgp_af' module. 
- Add support for 'dup-addr-detection' commands.
- Fix ansible-lint failures.
- Fix regression test cleanup tasks.

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
|  N/A |

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- sonic_bgp_af

##### OUTPUT

##### ADDITIONAL INFORMATION

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

2025-03-07 23:53 UTC, kerry-meyer requested changes
The proposed change set and the corresponding test results look great.

I am posting only a few minor change requests.

Thank you for adding this support and for taking the initiative, while implementing the new support, to do a lot of code cleanup and fixing of Ansible Lint errors.

2025-03-13 14:06 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_bgp_af.py
> +#   dup-addr-detection
The 'replaced' state example has been updated.

2025-03-13 14:06 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_bgp_af.py
> +                version_added: '3.0.0'
Addressed.

2025-03-13 14:07 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/facts/bgp_af/bgp_af.py
> +                                dup_addr_detection[option.replace('-', '_')] = dad_config['config'][option]
Addressed.

2025-03-14 00:04 UTC, kerry-meyer approved these changes
Thank you for implementing the requested incremental changes plus the additional re-ordering fixes.

The current proposed change set and corresponding test results look good.

Thanks again for adding the duplicate address detection support to the "BGP AF" resource module.

Approved.

2025-03-14 00:05 UTC, merged