lag_interfaces - Add support for 'graceful_shutdown', 'lacp_individual', 'min_links' and 'system_mac' options
ansible-collections/dellemc.enterprise_sonic pull request #475
Opened 2024-10-22 14:59 UTC by ArunSaravananBalachandran

##### SUMMARY

Incorporate the below changes in 'lag_interfaces' module.

- Add support for below options and update regression and UT cases to cover them:
  - graceful_shutdown
  - lacp_individual
  - min_links
  - system_mac
- Fix 'mode' value not retrieved in facts.
- Update 'replaced' and 'overridden' implementation to handle 'mode'.
- Fix ansible-lint failures.

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
| N/A |

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- sonic_lag_interfaces

##### OUTPUT

##### ADDITIONAL INFORMATION

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Regression report: [lag_interfaces_regression_report-2024-10-22-20-02-34.zip](https://github.com/user-attachments/files/17478231/lag_interfaces_regression_report-2024-10-22-20-02-34.zip)

2025-02-13 08:46 UTC, TafkaMax commented
What is the status on this PR?

2025-02-13 19:40 UTC, kerry-meyer commented
> What is the status on this PR?

Sorry for the delay. Some rework has been done on the underlying resource module to better accommodate these changes and to enhance the functionality of this resource module. This PR is now at the top of our prioritized review schedule. It will be reviewed (and probably merged) by the end of Tuesday 2/18.

2025-02-18 06:26 UTC, kerry-meyer requested changes
Thanks for the great job you have done of cleaning up and simplifying the code for this module while adding these new options.

I have posted only a few minor change requests and questions.

2025-02-18 11:37 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_lag_interfaces.py
> +# interface Eth1/6
Addressed.

2025-02-18 11:37 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_lag_interfaces.py
> +# interface Eth1/6
Addressed.

2025-02-18 11:37 UTC, ArunSaravananBalachandran commented on plugins/modules/sonic_lag_interfaces.py
> +  description: The generated configuration module invocation.
Have updated as suggested.

2025-02-18 11:38 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/facts/lag_interfaces/lag_interfaces.py
> +                        po_data[eth_segment['ifname']]['ethernet_segment']['esi_type'] = ESI_TYPE_PAYLOAD_TO_VALUE.get(eth_segment['esi_type'],
Default value for 'get' has been removed.

2025-02-18 11:38 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/lag_interfaces/lag_interfaces.py
> +        """Get a set of name of the members available in given LAG
Addressed.

2025-02-18 11:39 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/lag_interfaces/lag_interfaces.py
> +                esi_type = ESI_TYPE_VALUE_TO_PAYLOAD.get(esi_type, esi_type)
Argspec validation passes only supported values and hence default value for 'get' has been removed.

2025-02-18 11:40 UTC, ArunSaravananBalachandran commented on tests/regression/roles/sonic_lag_interfaces/defaults/main.yml
Regression and UT test cases have been updated to cover the above scenarios.

2025-02-18 18:22 UTC, kerry-meyer commented
Thank you for making these changes. All of the code changes look good and I have marked all of the pending "Issues" as "Resolved".

But the currently posted regression test results don't include the new test case. Please re-post the results to include the new test case.

Note: If it is too late in your day to do this, I will clone the PR branch and re-run the test so we can still get this PR merged today.

2025-02-19 05:03 UTC, kerry-meyer commented
Thank you for updating the posted regression test results.

All proposed changes and corresponding test results look good.

Approved.

2025-02-19 05:03 UTC, kerry-meyer approved these changes
Thank you for updating the posted regression test results.

All proposed changes and corresponding test results look good.

Approved.

2025-02-19 05:04 UTC, merged