Fix functionality to allow a value of 0 to be configured for the appropriate integer attributes and refactor STP module code
ansible-collections/dellemc.enterprise_sonic pull request #477
Opened 2024-10-29 20:31 UTC by stalabi1

##### SUMMARY

- I fixed the functionality of the code to allow a value of 0 to be configured for the appropriate integer attributes.
- I removed all of the default definitions from the argspec because the definitions were making some configuration cases impossible to implement, e.g. the deletion of an STP interface by interface name that has all defaults configured.
- I refactored the code to reduce the number of nested loops in the case of searching for instance matches. I condensed a few of the get delete request methods.
- I added more UT test cases to increase code coverage.
- I updated the facts code to properly handle empties allowing me to remove a few 'remove_empties' calls from config.

##### GitHub Issues

| GitHub Issue #472  |
| -------------- |

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

sonic_stp

##### OUTPUT

[regression-2024-11-11-14-59-56.html.pdf](https://github.com/user-attachments/files/17708910/regression-2024-11-11-14-59-56.html.pdf)
[merge_mst_id_0_output.log](https://github.com/user-attachments/files/17562751/merge_stp_output.log)

##### ADDITIONAL INFORMATION

Current SONiC behavior doesn't allow me to to configure any other mst-id when mst-id 0 is configured.
##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

2024-11-01 11:30 UTC, TafkaMax commented
Tested this branch and it fixes the issue I had.

2024-11-08 23:11 UTC, kerry-meyer requested changes
This change set, the additional test cases, and the corresponding test results looks good.

Thanks for adding efficiency improvements and reductions in the existing code along with the basic fix.

I am posting several minor comments/questions and change requests, but am not requesting any significant algorithmic changes.

2024-11-11 23:57 UTC, kerry-meyer commented on plugins/module_utils/network/sonic/config/stp/stp.py
> -            if hello_time == 2:
Thanks for explaining.

Resolved.

2024-11-12 00:07 UTC, kerry-meyer approved these changes
All current proposed changes and corresponding test results look good.

Thank you for not only fixing the problem described by the customer, but for taking the initiative to fix all related exposures in the STP resource module.

Approved.

2024-11-12 00:08 UTC, merged