Add FBS groups resource module
ansible-collections/dellemc.enterprise_sonic pull request #480
Opened 2024-11-12 22:17 UTC by stalabi1

##### SUMMARY

I added the FBS resource module. 
Please see [model PR](https://github.com/ansible-network/resource_module_models/pull/285).

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

sonic_fbs_groups

##### OUTPUT
[regression-2025-09-25-13-31-22.html.pdf](https://github.com/user-attachments/files/22547540/regression-2025-09-25-13-31-22.html.pdf)

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2025-01-24 21:27 UTC, awhaley-dell commented on plugins/module_utils/network/sonic/argspec/fbs_groups/fbs_groups.py
> +    """The arg spec for the sonic_fbs_groups module
```suggestion
    """
    The arg spec for the sonic_fbs_groups module
```
For a docstring of this class I recommend you should give the triple quotes its own line. 
It's not necessary but I believe this is more standard for pep python formatting.

2025-01-24 21:38 UTC, awhaley-dell commented on plugins/modules/sonic_fbs_groups.py
> +"""
```suggestion
"""

```
Could you add a newline to separate the variables within the modules file for readability?

2025-01-25 00:01 UTC, awhaley-dell approved these changes
Overall, everything looks good.

2025-09-25 08:53 UTC, ArunSaravananBalachandran requested changes

2025-09-25 08:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +                            group['group_type'] = cfg_group_type
Please include similar check and update 'threshold_type', since it could be absent in diff if only 'threshold_up' or 'threshold_down' is modified.

2025-09-25 08:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +            tmp_have = new_config
Variable is re-assigned immediately and can be removed.
```suggestion
            tmp_have = remove_empties(get_new_config(commands, tmp_have, TEST_KEYS_generate_config))
```

2025-09-25 08:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +            tmp_have = new_config
```suggestion
            tmp_have = remove_empties(get_new_config(commands, tmp_have, TEST_KEYS_generate_config))
```

2025-09-25 08:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +                            self._module.fail_json(msg='group_type is required')
Add validation and fail with error message for empty 'threshold_type'

2025-09-25 08:53 UTC, ArunSaravananBalachandran commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +                            if threshold_type:
Please verify if deletion of 'threshold_type' is supported while 'threshold_down' and 'threshold_up' are configured.

2025-09-25 19:10 UTC, stalabi1 commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +                            group['group_type'] = cfg_group_type
threshold_type is handled differently in the SONiC code so therefore no check is needed.

2025-09-25 19:21 UTC, stalabi1 commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +                            self._module.fail_json(msg='group_type is required')
See my above explanation for why I didn't include threshold_type in the get_modify_diff method. SONiC cvl will only throw error if threshold_type isn't already configured whereas for group_type and ip_address, cvl always throws an error message regardless if it's already configured. The get_modify_diff method fixes this SONiC bug for Ansible users.

2025-09-25 19:27 UTC, stalabi1 commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +                            if threshold_type:
Yes, it is supported. If threshold_type gets deleted while threshold_down and threshold_up are configured, then the behavior is it deletes all 3. I updated documentation and check mode to account for this behavior.

2025-09-25 20:38 UTC, stalabi1 commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +            tmp_have = new_config
Addressed.

2025-09-25 20:38 UTC, stalabi1 commented on plugins/module_utils/network/sonic/config/fbs_groups/fbs_groups.py
> +            tmp_have = new_config
Addressed.

2025-09-26 16:21 UTC, ArunSaravananBalachandran approved these changes

2025-09-26 23:32 UTC, kerry-meyer approved these changes
All current proposed changes and corresponding test results look good. Thank you for implementing the fbs_groups resource module for the enterprise_sonic Ansible resource module collection.

Approved.

2025-09-26 23:32 UTC, merged