Add support for host certificate deletion, display  and installation
ansible-collections/dellemc.enterprise_sonic pull request #483
Opened 2024-11-19 20:02 UTC by Tejaswi-Goel

SUMMARY
Add ansible support for SONiC PKI host certificates install, delete and display support. 

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
|N/A |

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
sonic_pki

##### OUTPUT
Regression Run Output

Detailed Regression Run Log

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

##### How Has This Been Tested?
Regression test with updated testcases.

2025-01-24 00:11 UTC, awhaley-dell commented on plugins/module_utils/network/sonic/config/pki/pki.py
> +POST = 'post'
```suggestion
POST = "post"
```
A little nitpick but for consistency you should use double quotes here

2025-01-24 00:13 UTC, awhaley-dell commented on plugins/module_utils/network/sonic/config/pki/pki.py
> +                                {"file-path": cert.get('file_path'),
```suggestion
                                {"file-path": cert.get("file_path"),
```
A little nitpick but for consistency you should use double quotes here

2025-01-24 00:14 UTC, awhaley-dell commented on plugins/module_utils/network/sonic/config/pki/pki.py
> +                                "fips-cert": cert.get('fips_cert')}}
```suggestion
                                "fips-cert": cert.get("fips_cert")}}
```
A little nitpick but for consistency you should use double quotes here

2025-01-24 00:26 UTC, awhaley-dell requested changes
I am asking for some small formatting consistency requests and explanations for a few conditional code snippets before I am ready to approve this PR.

2025-01-24 00:26 UTC, awhaley-dell commented on plugins/module_utils/network/sonic/config/pki/pki.py
> +        for cert in commands.get("host_cert") or []:
Can you explain why the empty list is necessary here? I don't immediately see a function of that _or_ clause here.

2025-01-24 00:26 UTC, awhaley-dell commented on plugins/module_utils/network/sonic/config/pki/pki.py
> +            for cert in commands.get("host_cert") or []:
Can you explain why the empty list is necessary here? I don't immediately see a function of that or clause here.

2025-01-24 00:26 UTC, awhaley-dell commented on plugins/module_utils/network/sonic/facts/pki/pki.py
> +                filenames = cert_data.get("filename", []) or []
Does the "or []" do anything in this statement? If the get() does not find anything with the key "filename" it will return an empty list. I am unclear on what the "or []" snippet does here.

2025-07-30 16:57 UTC, stalabi1 commented on plugins/module_utils/network/sonic/argspec/pki/pki.py
> +                        'fips_cert': {'type': 'bool', 'default': False},
```suggestion
                        'fips_cert': {'type': 'bool'},
```
We're trying to avoid specifying the default in the argspec

2025-07-30 16:58 UTC, stalabi1 commented on plugins/module_utils/network/sonic/facts/pki/pki.py
> +                fips_certs = cert_data.get("fips-cert", []) or []
```suggestion
                fips_certs = cert_data.get("fips-cert", False)
```
You can default fip_certs here instead of argspec

2025-07-30 17:33 UTC, stalabi1 commented on plugins/module_utils/network/sonic/config/pki/pki.py
Please help update the copyright to: "Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved."

Since overridden and replaced states aren't supported for host_cert, please use fail_json() to throw an error if the user  tries to do configuration for host_cert using those states e.g. "Overridden state is not supported for host_cert configuration. Please use merged and deleted states." Also, when you update the module/sonic_pki.py file please make note in the description for the host_cert dict that overridden and replaced states are not supported.

2025-08-13 21:03 UTC, stalabi1 commented on plugins/module_utils/network/sonic/config/pki/pki.py
> +            if isinstance(cert, dict) and cert.get("file_path") and cert.get("key_path"):
Please add a check here to ensure the user only specifies file_path, key_path and optionally fips_cert. If they don't specify only those options then please throw an error message i.e. "To merge host_cert configuration, specify only file_path, key_path, and optionally fips_cert.". Also, when you update the module/sonic_pki.py file please make note in the description for the host_cert.

2025-08-13 21:05 UTC, stalabi1 commented on plugins/module_utils/network/sonic/config/pki/pki.py
> +                if isinstance(cert, dict) and cert.get("file_name"):
Please add a check here to ensure the user only specifies file_name. If they don't specify only that option then please throw an error message i.e. "To delete host_cert configuration, specify only file_name.". Also, when you update the module/sonic_pki.py file please make note in the description for the host_cert.

2025-08-13 21:07 UTC, stalabi1 commented on tests/regression/roles/sonic_pki/defaults/main.yml
> +  - name: test_case_10
Seem's like it host_cert config is only deleted by file_name so no need to specify fips_cert.

2025-08-13 21:11 UTC, stalabi1 commented on plugins/module_utils/network/sonic/argspec/pki/pki.py
Please help update the copyright to: "Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved."
Please help delete lines 7-24.

2025-08-13 21:12 UTC, stalabi1 commented on plugins/module_utils/network/sonic/facts/pki/pki.py
Please help update the copyright to: "Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved."

2025-09-19 22:44 UTC, closed without merging

2025-09-19 22:44 UTC, Tejaswi-Goel commented
closing this pull request because the changes introduced — specifically host certificate install and delete functionality — do not align with the scope of the sonic_pki Ansible module, which is based on the sonic-pki.yang model. Since the sonic YANG model does not define these operations.