AAA bugfix and code refactor
ansible-collections/dellemc.enterprise_sonic pull request #495
Opened 2024-12-18 21:45 UTC by stalabi1

##### SUMMARY

- I updated the test cases and added a sleep in config to account for SONiC code changes. I opened a JIRA concerning a device lockout issue with the previous test cases so these test case changes may be reverted based on the outcome of JIRA.
- I updated the overridden state to handle the case of 'have' being a subset of 'want'.
- I refactored the delete state code to make use of 'get_diff_aaa' to calculate the deleted commands.
- I added a method to remove defaults.
- I applied Arun's suggestions on how to resolve ansible-lint errors for the regression files.

Please see[ model PR](https://github.com/ansible-network/resource_module_models/pull/209).

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

sonic_aaa

##### OUTPUT

[regression-2025-01-31-13-49-28.html.pdf](https://github.com/user-attachments/files/18624721/regression-2025-01-31-13-49-28.html.pdf)

##### Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [x] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

2025-01-30 23:21 UTC, awhaley-dell requested changes
Minor fixes requested; the code overall looks very solid.

2025-01-30 23:21 UTC, awhaley-dell commented on plugins/module_utils/network/sonic/config/aaa/aaa.py
>          """AAA module requires custom diff method due to overwritting of list in SONiC"""
```suggestion
        """AAA module requires custom diff method due to overwriting of list in SONiC"""
```
Small spelling error correction

2025-01-31 23:29 UTC, awhaley-dell approved these changes
Thanks for the fixes. Code looks good.

2025-02-11 00:06 UTC, kerry-meyer approved these changes
All currently proposed changes and the corresponding test results look good. Thank you for providing these fixes and improvements.

Approved.

2025-02-11 00:06 UTC, merged