Ansible support for MCLAG backup keepalive session feature specific yang leaf additions
ansible-collections/dellemc.enterprise_sonic pull request #496
Opened 2024-12-20 17:34 UTC by ravisekhar-akkineni

**SUMMARY**

Added ansible support for the new yang leafs added as part of the MCLAG backup keepalive session support.

##### GitHub Issues
List the GitHub issues impacted by this PR. If no Github issues are affected, please indicate this with "N/A".

| GitHub Issue # |
| -------------- |
| N/A|

**ISSUE TYPE**
- Feature Pull Request

**COMPONENT NAME**

sonic_mclag

 **OUTPUT

 ADDITIONAL INFORMATION**

 Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility or have provided any relevant "breaking_changes" descriptions in a "fragment" file in the "changelogs/fragments" directory of this repository.
- [ ] I have provided a summary for this PR in valid "fragment" file format in the "changelogs/fragments" directory of this repository branch. Reference : [Ansible Change Log Document](https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

**How Has This Been Tested?**

[regression-2024-12-19-09-50-47.html.pdf](https://github.com/user-attachments/files/18213612/regression-2024-12-19-09-50-47.html.pdf)

2025-01-31 06:04 UTC, kerry-meyer requested changes
The proposed code changes and corresponding test results look good, but I am posting some preliminary comments requesting changes mostly intended to improve the user documentation in the "module" file.

To fully evaluate the "config" file and regression test file changes, a revised posting of the regression test result file is needed. (The currently posted file has some missing columns that are needed to fully evaluate the test cases and results.) To avoid truncating the remaining columns, please "print" the regression test summary file in "landscape" orientation and scale it as needed to include all of the columns. After the revised regression test result file is posted, I will re-check the regression test "main.yml" file and also some parts of the "config" file based on what the results show for "before" and "after" configuration and may post some additional comments.

2025-02-03 06:28 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +      backup_keepalive_peer_address: 44.44.44.44
Repeating the above comment 

"This example is not provided to explain the entire list deletion. It captures the deletion of specific fileds as shown below,
source_address: 3.3.3.3
keepalive: 10
backup_keepalive_source_address: 31.31.31.31
backup_keepalive_peer_address: 44.44.44.44.

May be are you refering to lines between 573-631. Please confirm.

2025-02-03 14:18 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +          - MCLAG backup keepalive session interval in secs
Modified description to add supported range 1-60

2025-02-03 14:19 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Addressed

2025-02-03 14:19 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Addressed

2025-02-03 14:19 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Addressed

2025-02-03 14:19 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Addressed

2025-02-03 14:20 UTC, ravisekhar-akkineni commented on changelogs/fragments/496-MCLAG-Backup-Keepalive-Session-Ansible-Support.yaml
> +  - sonic_mclag - Added Ansible support for the yang leafs added as part of the  MCLAG Split Brain Detection and Recovery feature (https://github.com/ansible-collections/dellemc.enterprise_sonic/pull
Addressed

2025-02-03 14:20 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +          - The IPV4 backup-keepalive-source-ip to establish MCLAG backup keepalive session
Addressed

2025-02-03 14:27 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Addressed

2025-02-03 14:27 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Addressed

2025-02-03 14:51 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +      backup_keepalive_session_vrf: VrRed
Addressed

2025-02-03 14:52 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Addressed

2025-02-03 16:56 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
Added

2025-02-03 16:57 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Repeating the above comment

"This example is not provided to explain the entire list deletion. It captures the deletion of specific fileds as shown below,
source_address: 3.3.3.3
keepalive: 10
backup_keepalive_source_address: 31.31.31.31
backup_keepalive_peer_address: 44.44.44.44.

May be are you refering to lines between 573-631. Please confirm.

2025-02-03 17:08 UTC, ravisekhar-akkineni commented
> The proposed code changes and corresponding test results look good, but I am posting some preliminary comments requesting changes mostly intended to improve the user documentation in the "module" file.
> 
> To fully evaluate the "config" file and regression test file changes, a revised posting of the regression test result file is needed. (The currently posted file has some missing columns that are needed to fully evaluate the test cases and results.) To avoid truncating the remaining columns, please "print" the regression test summary file in "landscape" orientation and scale it as needed to include all of the columns. After the revised regression test result file is posted, I will re-check the regression test "main.yml" file and also some parts of the "config" file based on what the results show for "before" and "after" configuration and may post some additional comments.

I have added the results in landscape mode. Now all the columns are visible.

2025-02-04 02:42 UTC, kerry-meyer commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
The 573-631 is showing deletion of all mclag configuration (not selected lists within the configuration).

For this example, the meaning of specifying the key for a list (and no further details below the key) in a deletion playbook is that it is a request to delete the entire list specified by that key. In this case, for example, the "peer_gateway" dict contains only a "list" of "vlans". By specifying "vlans:" in the playbook, it specifies a request to delete the entire list of "vlans" for the "peer_gateway" dictionary. In this case, there is only one configured, but in the argspec, it can be seen that this one vlan is the only item on a "list" which could have included many vlans.

2025-02-04 05:41 UTC, kerry-meyer commented on plugins/modules/sonic_mclag.py
> +# Peer Address         :
Please delete the trailing space at the end of this line (868). It is causing the sanity tests to fail for this PR.

2025-02-04 05:50 UTC, kerry-meyer requested changes
Thank you for the changes you have added to address the posted review comments.

I have "Resolved" most of the "Issues" for this PR except the ones related to the list deletion example in the "module" file. For that, I have added an explanatory note on the first of these Issues.

There is also one very minor change needed to eliminate a trailing whitespace "sanity error" on line 868 of the "module" file.

All other proposed changes and test results look good now.

2025-02-04 06:16 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Removed the backup_keepalive_source_address: 31.31.31.31
backup_keepalive_peer_address: 44.44.44.44 and ensured that before and after state is same for the newly added fields

2025-02-04 06:17 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +      backup_keepalive_peer_address: 44.44.44.44
Removed the backup_keepalive_source_address: 31.31.31.31
backup_keepalive_peer_address: 44.44.44.44 and ensured that before and after state is same for the newly added fields

2025-02-04 06:17 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +#-----------------------------------
Removed the backup_keepalive_source_address: 31.31.31.31
backup_keepalive_peer_address: 44.44.44.44 and ensured that before and after state is same for the newly added fields

2025-02-04 06:17 UTC, ravisekhar-akkineni commented on plugins/modules/sonic_mclag.py
> +# Peer Address         :
Removed

2025-02-04 06:25 UTC, kerry-meyer approved these changes
Thank you for making these additional changes.

All current proposed changes and the corresponding test results look good.

Approved.

2025-02-04 06:26 UTC, merged